# Sample fixed data input
base_data = {
    'symmetry': 3,
    'radius': 75,
    'pattern': 0.0,
    'pan': 0.0,
    'disorder': 0.0,
    'randomSeed': 0,
    'zoom': 1.0,
    "showIntersections": True,
    "colorTiles": True,
    "orientationColoring": False,
    'stroke': 127,
    'showStroke': True,
    'rotate': 0,
    'hue': 342,
    'hueRange': 62,
    'contrast': 36,
    'sat': 74,
    'reverseColors': False,
    'tiles': [],
    'selectedLines': [],
    'selectedTiles': [],
    'epsilon': 1e-6,
    'inverseEpsilon': 1e6,
    'canvas1Resized': False,
    'canvas2Resized': False,
    'width': 800,
    'height': 800,
}